Traceback (most recent call last):
  File "/Users/butlerju/Library/Python/3.9/lib/python/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/butlerju/Library/Python/3.9/lib/python/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/butlerju/Library/Python/3.9/lib/python/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/butlerju/Library/Python/3.9/lib/python/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/Users/butlerju/Library/Python/3.9/lib/python/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/butlerju/Library/Python/3.9/lib/python/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
mnist_model = mnist_classification_model ()
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[10], line 1[0m
[0;32m----> 1[0m mnist_model [38;5;241m=[39m [43mmnist_classification_model[49m[43m [49m[43m([49m[43m)[49m

Cell [0;32mIn[9], line 6[0m, in [0;36mmnist_classification_model[0;34m()[0m
[1;32m      3[0m model [38;5;241m=[39m Sequential()
[1;32m      5[0m [38;5;66;03m# Add layers to the model[39;00m
[0;32m----> 6[0m model[38;5;241m.[39madd([43mFlatten[49m(input_shape[38;5;241m=[39m([38;5;241m28[39m, [38;5;241m28[39m)))  [38;5;66;03m# Flatten the 28x28 input images to a 1D vector[39;00m
[1;32m      7[0m model[38;5;241m.[39madd(Dense([38;5;241m128[39m, activation[38;5;241m=[39m[38;5;124m'[39m[38;5;124mrelu[39m[38;5;124m'[39m))  [38;5;66;03m# Fully connected layer with ReLU activation[39;00m
[1;32m      8[0m model[38;5;241m.[39madd(Dense([38;5;241m64[39m, activation[38;5;241m=[39m[38;5;124m'[39m[38;5;124mrelu[39m[38;5;124m'[39m))   [38;5;66;03m# Another fully connected layer with ReLU activation[39;00m

[0;31mNameError[0m: name 'Flatten' is not defined

